### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/dart-fortnite-api-wrapper#4]
**Is your feature request related to a problem? Please describe.**
We want to update our placeholder readme file!

**Describe the solution you'd like**
Here is what we want to add, completely replacing what we currently have

# Fortnite Api Wrapper

Fortnite api wrapper is a dart library for interacting with the [https://fortnite-api.com/](https://fortnite-api.com/).

## Installation

Use the package manager ... to install foobar.

```bash
pub get ....
```

## Usage

```dart
... TODO
```

## Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

## License
[MIT](LICENSE)

**Describe alternatives you've considered**
There is no documentation usage yet, and the package is not yet published, but feel free to add in more details to it.

**Comment by rustiever** [comment]
Hi! @AndreVarandas  can i solve this issue

**Comment by AndreVarandas** [comment]
Hi @rustiever thanks for reaching out! 
I'm assigning it to you 👍

**Comment by rustiever** [comment]
ok what should write in usage section? please don't mind i'm newbie
can we use some linters like effective_dart, lint, linter, pedantic etc? so that i can bring that icons to the readme

**Comment by AndreVarandas** [comment]
No issue, I'm also a newbie not even aware of the available linters for dart, but I'm all in for that!

**Comment by rustiever** [comment]
i resloved issue and created the pr, please merge to close the issue

**Comment by AndreVarandas** [comment]
Hi @rustiever I've just merged your PR. Would you like to change the issues link to the new issue link and to put the MIT license badge on a new line? Thank you!

**Comment by rustiever** [comment]
Hi @AndreVarandas , How to do that? i've done splitting the line in readme file and created the pr
